name: candy-pie-babylon.js to docs
on: push

jobs:
  run:
    name: candy-pie-babylon.js to docs II
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: copy js
        uses: canastro/copy-file-action@master
        with:
          source: "candy-pie-babylon.js"
          target: "docs/candy-pie-babylon.js"
      
      - name: copy index html
        uses: canastro/copy-file-action@master
        with:
          source: "docs_index.htm"
          target: "docs/index.htm"
          
      - name: copy playground html
        uses: canastro/copy-file-action@master
        with:
          source: "playground.htm"
          target: "docs/playground.htm"
      
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'force commit files into /docs'
          add: '*.* --force'
          cwd: './docs/'
